### ISSUE TITLE
NoMethodError: undefined method `create_view' for ActiveRecord::Schema

### ISSUE THREAD

**Issue by zillou** [thoughtbot/scenic#128]
I get this error when I was trying to run `rake db:schema:load`.

The `schema.rb` works fine with `rake db:setup`, but not with `rake db:create db:schema:load`.
Below is the stack trace I've got:

```
demo % rake db:create db:schema:load --trace
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
** Invoke db:schema:load (first_time)
** Invoke db:load_config
** Execute db:schema:load
-- enable_extension("plpgsql")
   -> 0.0233s
-- create_table("users", {:force=>:cascade})
   -> 0.0069s
-- create_view(:user_with_profiles, {:sql_definition=>"      SELECT users.name\n     FROM users;\n"})
rake aborted!
NoMethodError: undefined method `create_view' for #<ActiveRecord::Schema:0x007f9bb20710e8>
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:661:in `block in method_missing'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/private/tmp/demo/db/schema.rb:27:in `block in <top (required)>'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/schema.rb:41:in `instance_eval'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/schema.rb:41:in `define'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/schema.rb:61:in `define'
/private/tmp/demo/db/schema.rb:14:in `<top (required)>'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:274:in `each'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:244:in `block (3 levels) in <top (required)>'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/derrick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/derrick/.rbenv/versions/2.2.3/bin/rake:23:in `load'
/Users/derrick/.rbenv/versions/2.2.3/bin/rake:23:in `<main>'
Tasks: TOP => db:schema:load
```

**Comment by zillou** [comment]
It will work after upgraded Rails to 4.2.3.

**Comment by calebthompson** [comment]
@derekprior Did we make a change to how we `include` ourselves into ActiveRecord? I feel like we did and this could be related.

**Comment by derekprior** [comment]
I can't find the issue in Rails right now but I'm pretty certain the issue is this Rails bug: https://github.com/thiagopradi/octopus/issues/273

**Comment by calebthompson** [comment]
Every time I think that issue will go away, it comes back up. Haunting.

**Comment by zillou** [comment]
Shall we close this issue. but maybe it's better to add a warning message in the README about this issue?

**Comment by derekprior** [comment]
This is the actual rails issue for the problem: https://github.com/rails/rails/issues/19545

At this point, I'm happy enough to close this with no further action. If there are additional issues for people we can consider adding an FAQ entry.

**Comment by rschooley** [comment]
I am getting the above error in Rails 4.2.8 during a `schema:load` or during a `db:migrate` after a  `pg_restore`

**Comment by alegrria** [comment]
Hi guys.
I have the same issue with Rails 6.0.0
`bundle exec rake db:migrate
== 20191120131715 CreateReportings: migrating =================================
-- create_view(:reportings)`
results in `NoMethodError: undefined method `create_view' for #<CreateReportings:0x000055714ee359a8>`
I use scenic 1.5.1
